# Input configuration
numlockon=1
xkb_rules_layout=us,gb
xkb_rules_variant=dvorak,
xkb_rules_options=caps:swapescape,grp:ctrls_toggle

# Keybinds
bind=SUPER,Q,killclient
bind=SUPER,Return,spawn,kitty
bind=SUPER,W,spawn,firefox
